In [1]:
import numpy as np

In [17]:
#Creat 1d array, define type (memory size)
a = np.array([1, 2, 3], dtype = 'int32')
a

array([1, 2, 3], dtype=int32)

In [5]:
#Create 2d array
b = np.array([[1.0, 2.3, 4.5], [3.2, 6.5, 7.2]])
b

array([[1. , 2.3, 4.5],
       [3.2, 6.5, 7.2]])

In [9]:
#Get Dimension
a.ndim

1

In [11]:
#Get Shape
# axis = (row, column, depth)
b.shape

(2, 3)

In [19]:
#Get Type
a.dtype

dtype('int32')

In [18]:
#Get Size
a.itemsize

4

In [21]:
#Get number of elements
b.size

6

In [26]:
#Get total size
a.itemsize*a.size
a.nbytes

12

In [27]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [28]:
#Get a specific element name of array[r,c] where r = row and c = column
a[1, 5]

13

In [29]:
#Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [30]:
#Get a specific column
a[:, 2]

array([ 3, 10])

In [31]:
#stepwise name of array[row, startindex:endindex:stepsize] or vice versa
a[0, 1:6:2]

array([2, 4, 6])

In [33]:
#replace an element or elements in an array
a[1,5] = 20
a[:,2] = [1,2]
#notice how the order of the [1,2] is reflected in the substitution in the array below down the 2 column
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [34]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [35]:
# Get specific element (work outside in); b [group, row, column]
b[0,1,1]

4